---
title: "WEME Nest Survival"
author: "Justin Clarke"
date: "2022-08-31"
output: html_document
---

This is the baseline code for each species. I can just either change the species name for this or copy and paste before changing the species for each species.

```{r}
setwd("~/Git/NDSU/RMARK")                                                       # set the working directory

library(ggplot2)
library(vegan)
library(tidyverse)
library(RMark)

windowsFonts(my_font = windowsFont("Gandhi Sans"))

nest <- read.csv("~/Git/NDSU/RMARK/Working Data/RMarknesting.csv", 
                 row.names=1)

WEME.surv <- filter(nest, 
                    Spec=="WEME")                                         # select out only WEME nests

WEME.surv$AgeDay1 <- WEME.surv$AgeFound - WEME.surv$FirstFound + 1
WEME.surv$Year <- as.factor(WEME.surv$Year)
WEME.surv$cTreat <- as.factor(WEME.surv$cTreat)

create.stage.var=function(data,agevar.name,stagevar.name,time.intervals,cutoff)
{
nocc=length(time.intervals)
age.mat=matrix(data[,agevar.name],nrow=dim(data)[1],ncol=nocc-1)
age.mat=t(t(age.mat)+cumsum(c(0,time.intervals[1:(nocc-2)])))
stage.mat=t(apply(age.mat,1,function(x) as.numeric(x<=cutoff)))
stage.mat=data.frame(stage.mat)
names(stage.mat)=paste(stagevar.name,1:(nocc-1),sep="")
return(stage.mat)
}

x <- create.stage.var(WEME.surv, 
                         "AgeDay1", 
                         "Incub", 
                         rep(1,max(WEME.surv$LastChecked)), 
                         14)

WEME.surv <- cbind(WEME.surv, x)
```

```{r}
WEME.pr <- process.data(WEME.surv,
                        nocc=max(WEME.surv$LastChecked),
                        groups = c("cTreat", 
                                   "Year"),
                        model="Nest")

# candidate models for the null vs. treatment model
WEME1.run <- function()
{
  # 1. a model for constant daily survival rate
  S.Dot = list(formula =  ~1)
  
  # 2. DSR varies with current treatment
  S.cTreat = list(formula = ~1 + cTreat)
  
  # 3. DSR varies with year
  S.year = list(formula = ~1 + Year)
  
  # 4. DSR varies With year interacting with treatment (treatment identity varies by year)
  S.treatyear = list(formula = ~1 + cTreat:Year)
  
  WEME.model.list = create.model.list("Nest")
  WEME1.results = mark.wrapper(WEME.model.list,
                            data = WEME.pr,
                            adjust = FALSE,
                            delete = TRUE)
}

#results of candidate model set 
#all results
WEME1.results <- WEME1.run()
WEME1.results

WEME1.results$S.Dot$results$beta
WEME1.results$S.year$results$beta

#candidate model set for time trends
WEME2.run <- function()
{
  # 1. DSR varies with time
  S.time = list(formula = ~1 +  Time)
  
  # 3. DSR varies with quadratic effect of date
  S.quad = list(formula = ~1 + Time + I(Time^2))
  
  # 4. DSR varies across stages
  S.stage = list(formula = ~1 + Incub)
  
  # 1. a model for constant daily survival rate
  S.Dot = list(formula =  ~1)
  
  WEME.model.list = create.model.list("Nest")
  WEME2.results = mark.wrapper(WEME.model.list,
                            data = WEME.pr,
                            adjust = FALSE,
                            delete = FALSE)
}

#results of candidate model set 
#all results
WEME2.results <- WEME2.run()
WEME2.results

WEME2.results$S.Dot$results$beta
WEME2.results$S.time$results$beta
WEME2.results$S.stage$results$beta

#candidate model set for parasitism and nest stage
WEME3.run <- function()
{
  # 1. DSR varies with BHCO number
  S.bhco = list(formula = ~1 + cTreat + Time + BHCONum)
  
  # 1. a model for constant daily survival rate
  S.Dot = list(formula =  ~1)
  
  WEME.model.list = create.model.list("Nest")
  WEME3.results = mark.wrapper(WEME.model.list,
                            data = WEME.pr,
                            adjust = FALSE,
                            delete = TRUE)
}

#results of candidate model set 
#all results
WEME3.results <- WEME3.run()
WEME3.results

WEME3.results$S.Dot$results$beta
WEME3.results$S.bhco$results$beta

#candidate model set for parasitism and nest stage
WEME4.run <- function()
{
  # 1. DSR varies with KBG
  S.kbg = list(formula =  ~1 + KBG)
  
  # 2. DSR varies with Smooth Brome (correlated with KBG and Litter Depth)
  S.smooth.brome = list(formula = ~1 + SmoothB)
  
  # 3. DSR varies with Litter (correlated with KBG)
  S.lit = list(formula =  ~1 + Litter)
  
  # 4. DSR varies with Bare
  S.bare = list(formula =  ~1 + Bare)
  
  # 5. DSR varies with Forb
  S.forb = list(formula =  ~1 + Forb)
  
  # 6. DSR varies with Grasslike  (correlated with KBG)
  S.grass = list(formula =  ~1 + Grasslike)
  
  # 7. DSR varies with Woody
  S.woody = list(formula =  ~1 + Woody)
  
  # 8. DSR varies with Litter Depth (correlated with VOR)
  S.litdep = list(formula =  ~1 + LitterD)
  
  # 9. DSR varies with Veg Height (correlated with VOR)
  S.height = list(formula =  ~1 + Veg.Height)
  
  # 10. DSR varies with VOR
  S.vor = list(formula =  ~1 + VOR)
  
  # 11. DSR varies with litter and Veg Height
  S.litheight = list(formula = ~1 + Litter + Veg.Height)
  
  # 12. DSR varies with woody and litter depth
  S.woodylitdep = list(formula = ~1 + Woody + LitterD)
  
  # 13. DSR varies with KBG and litter depth
  S.kbglitdep = list(formula = ~1 + KBG + LitterD)
  
  # 14. DSR varies with KBG and Veg.Height
  S.kbgheight = list(formula = ~1 + KBG + Veg.Height)
  
  # 15. DSR varies with woody and Veg Height
  S.woodyheight = list(formula = ~1 + Woody + Veg.Height)
  
  # 1. a model for constant daily survival rate
  S.Dot = list(formula =  ~1)
  
  WEME.model.list = create.model.list("Nest")
  WEME4.results = mark.wrapper(WEME.model.list,
                            data = WEME.pr,
                            adjust = FALSE,
                            delete = FALSE)
}

#results of candidate model set 
#all results
WEME4.results <- WEME4.run()
WEME4.results

WEME4.results$S.bare$results$beta
WEME4.results$S.kbgheight$results$beta
WEME4.results$S.height$results$beta
WEME4.results$S.litheight$results$beta

WEME4.results$S.bare$results$real
```

```{r}
WEME.mod <- mark(WEME.surv, 
                 nocc=max(WEME.surv$LastChecked), 
                 model = "Nest", 
                 model.parameters = list(S = list(formula =  ~1 + Bare)))

WEME4.beta <- WEME4.results$S.bare$results$beta
WEME4.beta

WEME.top <- rownames_to_column(WEME4.beta, 
                               "Variable")
WEME.top <- rename(WEME.top, 
                   "Coefficient"="estimate")

WEME.top[,1] <- gsub("S:", "", WEME.top[,1])
str(WEME.top)

WEME.top$SEup <- WEME.top$Coefficient + WEME.top$se
WEME.top$SElow <- WEME.top$Coefficient - WEME.top$se

WEME.plot <- ggplot(WEME.top, aes(x = Variable,
                                  y = Coefficient)) +
  geom_hline(yintercept = 0,
             colour = gray(1/2), 
             lty = 2) +
  geom_point(aes(x = Variable,
                 y = Coefficient),
             size = 5) +
  geom_errorbar(aes(x = Variable,
                    ymin = lcl,
                    ymax = ucl),
                width = .5,
                size = 1) +
  ggtitle("WEME Beta Coefficient") +
  theme(panel.grid.major = element_blank(),                                     # remove the vertical grid lines
        panel.grid.minor = element_blank(),                                     # remove the horizontal grid lines
        panel.background = element_rect(fill="white",                           # make the interior background transparent
                                        colour = NA),                           # remove any other colors
        plot.background = element_rect(fill="white",                            # make the outer background transparent
                                       colour=NA),                              # remove any other colors
        axis.line = element_line(colour = "black"),                             # color the x and y axis
        axis.text = element_text(size=12, 
                                 colour = "black"),                    # color the axis text
        axis.ticks = element_line(colour = "black"),                            # change the colors of the axis tick marks
        text=element_text(size=12,                                              # change the size of the axis titles
                          colour = "black")) +                                  # change the color of the axis titles
  coord_flip()
                       
WEME.plot
```

```{r}
plotdata <- WEME4.results$S.bare

WEME.ddl <- make.design.data(WEME.pr)
WEME.ddl <- as.data.frame(WEME.ddl)

minbare <- min(WEME.surv$Bare)
maxbare <- max(WEME.surv$Bare)
Bare.values = seq(from = minbare, 
                    to = maxbare, 
                    length = 100)

bare.pred <- covariate.predictions(plotdata,
                                   data=data.frame(Bare=Bare.values),
                                   indices = 1)

bare.pred$estimates$Group <- "WEME"

WEMEbare.plot <- ggplot(bare.pred$estimates,
                    aes(x = covdata,
                        y = estimate,
                        fill = Group)) +
  geom_line(size = 1.5,
            aes(colour = Group)) +
  geom_ribbon(aes(ymin = lcl, 
                  ymax = ucl), 
              alpha = 0.1) +
  scale_colour_manual(values = c('black')) +
  scale_fill_manual(values = c('black')) +
  xlab("Bare Cover") +
  ylab("Estimated DSR") +
  ylim(0, 1) + 
  theme(plot.title = element_text(family="my_font",                             # select the font for the title
                                  size=16,
                                  hjust=.5),
        panel.grid.major = element_blank(),                                     # remove the vertical grid lines
        panel.grid.minor = element_blank(),                                     # remove the horizontal grid lines
        panel.background = element_rect(fill=NA,                     # make the interior background transparent
                                        colour = NA),                           # remove any other colors
        plot.background = element_rect(fill=NA,                      # make the outer background transparent
                                       colour=NA),                              # remove any other colors
        axis.line = element_line(colour = "black"),                             # color the x and y axis
        axis.text.y = element_text(size=12, colour = "black"),                    # color the axis text
        axis.text.x = element_text(size=12, colour = "black"),
        axis.ticks = element_line(colour = "black"),                            # change the colors of the axis tick marks
        text=element_text(size=12,                                              # change the size of the axis titles
                          colour = "black"),                                    # change the color of the axis titles
        legend.position = "none") +                                             # remove the legend
  labs(title = "Western Meadowlark")

WEME.plot
WEMEbare.plot

ggsave(WEME.plot,
       filename = "~/Git/NDSU/RMARK/Figures/WEMEbeta.png",
       dpi = "print",
       bg = "white",
       height = 6,
       width = 6)

ggsave(WEMEbare.plot,
       filename = "~/Git/NDSU/RMARK/Figures/WEMEbare.png",
       dpi = "print",
       bg = "white",
       height = 6,
       width = 6)
```

```{r}
# If you want to clean up the mark*.inp, .vcv, .res and .out
#  and .tmp files created by RMark in the working directory,
#  execute 'rm(list = ls(all = TRUE))' - see 2 lines below.
# NOTE: this will delete all objects in the R session.
 rm(list = ls(all=TRUE))
# Then, execute 'cleanup(ask = FALSE)' to delete orphaned output
#  files from MARK. Execute '?cleanup' to learn more
 cleanup(ask = FALSE)
```